# Generated by Django 5.2.7 on 2025-10-14 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Аватар')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/users/%Y/%m/', verbose_name='Обложка профиля')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Twitter')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='GitHub')),
                ('linkedin', models.CharField(blank=True, max_length=100, verbose_name='LinkedIn')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('show_email', models.BooleanField(default=False, verbose_name='Показывать email')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('auto', 'Авто')], default='auto', max_length=10, verbose_name='Тема')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='Подписчики')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='Подписки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='На кого подписан')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower', '-created_at'], name='users_follo_followe_b6ba3d_idx'), models.Index(fields=['following', '-created_at'], name='users_follo_followi_f424c9_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
