# Generated by Django 5.2.7 on 2025-10-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Изображение иконки'),
        ),
    ]
