# Generated by Django 5.2.7 on 2025-10-16 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_category_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_video',
            field=models.FileField(blank=True, help_text='Видео обложка (mp4, webm). Если указано, будет использоваться вместо изображения', null=True, upload_to='articles/covers/videos/%Y/%m/', verbose_name='Обложка (видео)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/covers/%Y/%m/', verbose_name='Обложка (изображение)'),
        ),
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10, verbose_name='Тип медиа')),
                ('file', models.FileField(upload_to='articles/media/%Y/%m/', verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('alt_text', models.CharField(blank=True, help_text='Для изображений', max_length=200, verbose_name='Alt текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='articles.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Медиа-файл',
                'verbose_name_plural': 'Медиа-файлы',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
