# Generated by Django 5.2.7 on 2025-10-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_cover_video_alter_article_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_video_url',
            field=models.URLField(blank=True, help_text='URL видео или YouTube (например: https://www.youtube.com/watch?v=... или youtube:VIDEO_ID)', max_length=500, verbose_name='Обложка (видео по URL)'),
        ),
    ]
