# Generated by Django 5.2.7 on 2025-10-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_cover_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_video_url',
            field=models.CharField(blank=True, help_text='URL видео или YouTube (например: https://www.youtube.com/watch?v=... или youtube:VIDEO_ID)', max_length=500, verbose_name='Обложка (видео по URL)'),
        ),
    ]
