# Generated by Django 5.2.7 on 2025-10-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_cover_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-is_pinned', 'pin_order', '-published_at', '-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='pin_order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения закрепленной статьи (1 - вверху, 2 - второй и т.д.). 0 - не закреплено', verbose_name='Порядок закрепления'),
        ),
    ]
