# Generated by Django 5.2.7 on 2025-10-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_options_article_pin_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='URL'),
        ),
    ]
